language: node_js
node_js:
  - "4.2.6"
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    branch: master
